name: "Autoglot Translate"
description: "Translate Xcode String Catalogs (.xcstrings) and web localization files using Autoglot"
author: "autoglot"

branding:
  icon: "globe"
  color: "blue"

inputs:
  api-key:
    description: "Your Autoglot API key (get one at https://autoglot.app/dashboard/api-keys)"
    required: true
  paths:
    description: "Paths to search for translation files. Supports glob patterns. Leave empty to find all .xcstrings files."
    required: false
    default: ""
  languages:
    description: 'Comma-separated list of target languages (e.g., "de,fr,ja")'
    required: true
  api-url:
    description: "Autoglot API URL (default: https://api.autoglot.app)"
    required: false
    default: "https://api.autoglot.app"

  # GitHub PR configuration (optional if Autoglot GitHub App is installed)
  github-token:
    description: "GitHub PAT for creating PRs (optional if GitHub App is installed)"
    required: false
    default: ""
  branch-name:
    description: "Branch name for translations (ignored when output-mode is commit-to-branch)"
    required: false
    default: "autoglot/translations"
  base-branch:
    description: "Base branch to create PR against"
    required: false
    default: "main"
  commit-message:
    description: "Commit message for translation updates"
    required: false
    default: "chore(i18n): update translations"
  pull-request-title:
    description: "PR title for translation updates (ignored when output-mode is commit-to-branch)"
    required: false
    default: "chore(i18n): update translations"
  output-mode:
    description: "Output mode: 'create-pr' (default) creates a new PR, 'commit-to-branch' commits directly to a branch. Omit head-branch to commit directly to base-branch."
    required: false
    default: "create-pr"
  head-branch:
    description: "Branch to commit translations to. Defaults to base-branch when output-mode is commit-to-branch."
    required: false
    default: ""
  wait-for-completion:
    description: "Wait for translation job to complete before exiting. Defaults to true for commit-to-branch mode, false otherwise."
    required: false
    default: ""

outputs:
  job-id:
    description: "Batch job ID for tracking (or 'skipped' if this was our own commit)"
  skipped:
    description: "Whether the translation was skipped (true if triggered by our own commit)"
  pr-number:
    description: "Pull request number (if wait-for-completion is enabled and PR was created)"

runs:
  using: "composite"
  steps:
    - name: Submit Translation Job
      shell: bash
      env:
        AUTOGLOT_API_KEY: ${{ inputs.api-key }}
        AUTOGLOT_API_URL: ${{ inputs.api-url }}
        INPUT_PATHS: ${{ inputs.paths }}
        TARGET_LANGUAGES: ${{ inputs.languages }}
        GITHUB_PAT: ${{ inputs.github-token }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_BASE_BRANCH: ${{ inputs.base-branch }}
        BRANCH_NAME: ${{ inputs.branch-name }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
        PR_TITLE: ${{ inputs.pull-request-title }}
        OUTPUT_MODE: ${{ inputs.output-mode }}
        HEAD_BRANCH: ${{ inputs.head-branch || github.head_ref }}
        TRIGGER_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        WAIT_FOR_COMPLETION: ${{ inputs.wait-for-completion }}
      run: |
        ${{ github.action_path }}/translate.sh
