name: "Autoglot Translate"
description: "Translate Xcode String Catalogs (.xcstrings) using Autoglot"
author: "autoglot"

branding:
  icon: "globe"
  color: "blue"

inputs:
  api-key:
    description: "Your Autoglot API key (get one at https://autoglot.app/dashboard/api-keys)"
    required: true
  file:
    description: "Path to .xcstrings file(s). Use glob pattern or leave empty to find all"
    required: false
    default: ""
  languages:
    description: 'Comma-separated list of target languages (e.g., "de,fr,ja")'
    required: true
  api-url:
    description: "Autoglot API URL (default: https://api.autoglot.app)"
    required: false
    default: "https://api.autoglot.app"

  # GitHub PR configuration (optional if Autoglot GitHub App is installed)
  github-token:
    description: "GitHub PAT for creating PRs (optional if GitHub App is installed)"
    required: false
    default: ""
  branch-name:
    description: "Branch name for translations"
    required: false
    default: "autoglot/translations"
  base-branch:
    description: "Base branch to create PR against"
    required: false
    default: "main"
  commit-message:
    description: "Commit message for translation updates"
    required: false
    default: "chore(i18n): update translations"
  pull-request-title:
    description: "PR title for translation updates"
    required: false
    default: "chore(i18n): update translations"

outputs:
  job-id:
    description: "Batch job ID for tracking"

runs:
  using: "composite"
  steps:
    - name: Submit Translation Job
      shell: bash
      env:
        AUTOGLOT_API_KEY: ${{ inputs.api-key }}
        AUTOGLOT_API_URL: ${{ inputs.api-url }}
        INPUT_FILE: ${{ inputs.file }}
        TARGET_LANGUAGES: ${{ inputs.languages }}
        GITHUB_PAT: ${{ inputs.github-token }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_BASE_BRANCH: ${{ inputs.base-branch }}
        BRANCH_NAME: ${{ inputs.branch-name }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
        PR_TITLE: ${{ inputs.pull-request-title }}
      run: |
        ${{ github.action_path }}/translate.sh
